---
name: databaseconnectors
---
Injector:
  MySQLPDODatabase:
    class: 'MySQLDatabase'
    properties:
      connector: %$PDOConnector
      schemaManager: %$MySQLSchemaManager
      queryBuilder: %$MySQLQueryBuilder
  MySQLDatabase:
    class: 'MySQLDatabase'
    properties:
      connector: %$MySQLiConnector
      schemaManager: %$MySQLSchemaManager
      queryBuilder: %$MySQLQueryBuilder
  MySQLiConnector:
    class: 'MySQLiConnector'
    type: prototype
  PDOConnector:
    class: 'PDOConnector'
    type: prototype
  Int:
    class: DBInt
  int:
    class: DBInt
  INT:
    class: DBInt
  Float:
    class: DBFloat
  float:
    class: DBFloat
  FLOAT:
    class: DBFloat
